name: Build-Manual

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
        os: [ ubuntu-20.04, windows-latest]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Set up Go (needed for ghr)
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.0

      - name: Install ghr (needed to publish releases)
        run: |
          go install github.com/tcnksm/ghr@latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./src/requirements.txt
          python -m pip install -r ./src/SEBASTiAn/excelify/requirements.txt

      - name: Run tests
        run: |
          pytest --verbose --cov=./ --cov-report xml

      - name: Generate excel file with the details of the vulnerabilities
        run: |
          cd ./src/
          python -m SEBASTiAn.excelify.excelify

      - name: Update the latest release
        run: |
          ghr -t ${{ secrets.GITHUB_TOKEN }} \
            -b "${{ github.event.head_commit.message }}" \
            -recreate documentation-latest ./src/SEBASTiAn/excelify/xlsx/
